# Generated by Django 3.0.4 on 2020-03-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=10)),
                ('product', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('unitprice', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('tax', models.IntegerField(blank=True)),
                ('descript', models.CharField(blank=True, max_length=500)),
                ('total', models.IntegerField()),
                ('invnumber', models.IntegerField(blank=True)),
                ('amountpaid', models.IntegerField()),
                ('paymode', models.CharField(max_length=50)),
                ('receiptnum', models.IntegerField(blank=True)),
                ('balancedue', models.IntegerField(blank=True)),
                ('balduedate', models.DateTimeField(blank=True)),
            ],
        ),
    ]
